### ISSUE TITLE
Not recognising nanopolish file

### ISSUE THREAD

**Issue by lab-rat-kid** [a-slide/pycoMeth#33]
CpG_Aggregate is not recognising the tsv file output from nanopolish. This is what I get:

```
$ pycoMeth CpG_Aggregate -i results/methylation/nanopolish/C1_meth_calls.tsv -f results/input/genome/genome.fa -b results/methylation/pycometh_cpg_agg/C1_CpG_Agg.bed -t results/methylation/pycometh_cpg_agg/C1_CpG_Agg.tsv -s Control_1 -v -p
Cannot import dependencies required for static image export
## Checking options and input files ##
	[DEBUG]: Options summary
	[DEBUG]: 	Package name: pycoMeth
	[DEBUG]: 	Package version: 0.4.13
	[DEBUG]: 	Timestamp: 2020-07-16 17:09:31.520055
	[DEBUG]: 	nanopolish_fn: ['results/methylation/nanopolish/C1_meth_calls.tsv']
	[DEBUG]: 	ref_fasta_fn: results/input/genome/genome.fa
	[DEBUG]: 	output_bed_fn: results/methylation/pycometh_cpg_agg/C1_CpG_Agg.bed
	[DEBUG]: 	output_tsv_fn: results/methylation/pycometh_cpg_agg/C1_CpG_Agg.tsv
	[DEBUG]: 	min_depth: 10
	[DEBUG]: 	sample_id: Control_1
	[DEBUG]: 	min_llr: 2
	[DEBUG]: 	verbose: True
	[DEBUG]: 	quiet: False
	[DEBUG]: 	progress: True
	[DEBUG]: 	kwargs
	[DEBUG]: 		subcommands: CpG_Aggregate
	[DEBUG]: 		func: <function CpG_Aggregate at 0x7fd6dc2d44d0>
## Parsing methylation_calls file ##
	[DEBUG]: Opening file results/methylation/nanopolish/C1_meth_calls.tsv in normal mode
	[DEBUG]: Reading header from file: results/methylation/nanopolish/C1_meth_calls.tsv
	[DEBUG]: Column names from header: 'chromosome / start / end / read_name / log_lik_ratio / log_lik_methylated / log_lik_unmethylated / num_calling_strands / num_cpgs / sequence'
	[DEBUG]: Input file type: unknown
	[DEBUG]: Closing file:results/methylation/nanopolish/C1_meth_calls.tsv
Traceback (most recent call last):
  File "/home/tylerstevenson/miniconda3/bin/pycoMeth", line 8, in <module>
    sys.exit(main())
  File "/home/tylerstevenson/miniconda3/lib/python3.7/site-packages/pycoMeth/__main__.py", line 115, in main
    args.func(**vars(args))
  File "/home/tylerstevenson/miniconda3/lib/python3.7/site-packages/pycoMeth/CpG_Aggregate.py", line 69, in CpG_Aggregate
    raise pycoMethError("Invalid input file type passed (nanopolish_fn). Expecting Nanopolish call_methylation output TSV file")
pycoMeth.common.pycoMethError: Invalid input file type passed (nanopolish_fn). Expecting Nanopolish call_methylation output TSV file
```
The files were generated using nanopolish version 0.9.0
Any help would be greatly appretiated!

**Comment by a-slide** [comment]
Hi @lab-rat-kid 
Something might have changed in nanopolish
Could you copy the first lines of the input file you are using ?
Thanks

**Comment by lab-rat-kid** [comment]
Thanks for seeing this so quickly!!!
This is what nanopolish call-methylation gives me:
```
chromosome	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_motifs	sequence
chr1	723919	723919	47667ea2-4173-45e7-9db2-5fc9713bfeb7	2.74	-135.85	-138.59	1	1	CAGTTCGCTCT
chr1	723946	723956	47667ea2-4173-45e7-9db2-5fc9713bfeb7	3.43	-137.76	-141.19	1	2	AGAAACGAGAATATCCGTATA
chr1	723972	723972	47667ea2-4173-45e7-9db2-5fc9713bfeb7	4.4	-133.85	-138.26	1	1	GTACACGCATG
chr1	723991	723991	47667ea2-4173-45e7-9db2-5fc9713bfeb7	3.3	-120.24	-123.54	1	1	AGTCTCGTCCA
chr1	724063	724066	47667ea2-4173-45e7-9db2-5fc9713bfeb7	-0.37	-118.19	-117.82	1	2	CCACACGACGGAAA
chr1	724106	724122	47667ea2-4173-45e7-9db2-5fc9713bfeb7	-4.17	-298.19	-294.02	1	3	TGACACGCCTAACGACAGAGACGACCC
chr1	724140	724140	47667ea2-4173-45e7-9db2-5fc9713bfeb7	0.88	-175.89	-176.77	1	1	TGCCACGCTGA
```

Thanks!

**Comment by lab-rat-kid** [comment]
Thanks so seeing this so quickly!
This is what nanopolish gives:
```
chromosome	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_cpgs	sequence
chr1	914685	914685	f25d056b-e46d-4f49-b0e1-6808e3ecc999	-0.37	-130.99	-130.62	1	1	CAGACCGTCAG
chr1	914711	914711	f25d056b-e46d-4f49-b0e1-6808e3ecc999	-0.34	-205.69	-205.35	1	1	TCCTACGGGTT
chr1	914723	914723	f25d056b-e46d-4f49-b0e1-6808e3ecc999	-8.56	-115.41	-106.85	1	1	CCTGCCGAGGT
chr1	914738	914738	f25d056b-e46d-4f49-b0e1-6808e3ecc999	3.48	-95.83	-99.31	1	1	AACCCCGGCAC
chr1	914781	914781	f25d056b-e46d-4f49-b0e1-6808e3ecc999	1.71	-140.95	-142.65	1	1	CCCCTCGGAGA
chr1	230961	230976	24486120-e4eb-4068-b35f-9a87bbbe042c	0.57	-336.70	-337.28	1	3	AAATGCGTCTCGGGAGCAGCCGTGTT
```
I've tried changing num_cpgs to num_motifs as I saw your script indicated this might be this problem. It didn't help.

Thanks!

**Comment by lab-rat-kid** [comment]
When I add a column called `strand` filled with `+`, and change `num_cpgs` to `um_motifs`.

**Comment by lab-rat-kid** [comment]
So doing a test with some nanopolish output files that I modified as I mentioned above, I get through CpG Aggregate and Interval Aggregate, then at Meth Comp I get this:

```
pycoMeth Meth_Comp -i results/methylation/pycometh_int_agg/test.tsv, results/methylation/pycometh_int_agg/test2.tsv -f results/input/genome/genome.fa -b results/methylation/pycometh_meth_comp/test.bed -t results/methylation/pycometh_meth_comp/test.tsv -s test_1, test_2 -v -p
Cannot import dependencies required for static image export
## Checking options and input files ##
	[DEBUG]: Options summary
	[DEBUG]: 	Package name: pycoMeth
	[DEBUG]: 	Package version: 0.4.13
	[DEBUG]: 	Timestamp: 2020-07-16 18:33:50.572452
	[DEBUG]: 	aggregate_fn_list: ['results/methylation/pycometh_int_agg/test.tsv,', 'results/methylation/pycometh_int_agg/test2.tsv']
	[DEBUG]: 	ref_fasta_fn: results/input/genome/genome.fa
	[DEBUG]: 	output_tsv_fn: results/methylation/pycometh_meth_comp/test.tsv
	[DEBUG]: 	output_bed_fn: results/methylation/pycometh_meth_comp/test.bed
	[DEBUG]: 	max_missing: 0
	[DEBUG]: 	min_diff_llr: 2
	[DEBUG]: 	sample_id_list: ['test_1,', 'test_2']
	[DEBUG]: 	pvalue_adj_method: fdr_bh
	[DEBUG]: 	pvalue_threshold: 0.01
	[DEBUG]: 	only_tested_sites: False
	[DEBUG]: 	verbose: True
	[DEBUG]: 	quiet: False
	[DEBUG]: 	progress: True
	[DEBUG]: 	kwargs
	[DEBUG]: 		subcommands: Meth_Comp
	[DEBUG]: 		func: <function Meth_Comp at 0x7fc3bfa50d40>
	[DEBUG]: Loading Fasta index:results/input/genome/genome.fa
	[DEBUG]: Found 5466 reference sequences
	[DEBUG]: Coordinate reference summary
	[DEBUG]: 	*Name:chr1	ID:0	Length:275406953
	[DEBUG]: 	*Name:chr10	ID:1	Length:86377204
```
........................
```
	[DEBUG]: 	*Name:chrX	ID:5465	Length:135185801
	[DEBUG]: Checking required output
	[DEBUG]: Pairwise comparison mode (Mann_Withney test)
	[DEBUG]: No missing samples allowed for 2 samples comparison
## Parsing files ##
	Reading input files header and checking consistancy between headers
	[DEBUG]: Column names from header: ''
	[DEBUG]: Input file type: unknown
	[DEBUG]: Opening file results/methylation/pycometh_int_agg/test2.tsv in normal mode
	[DEBUG]: Reading header from file: results/methylation/pycometh_int_agg/test2.tsv
	[DEBUG]: Column names from header: 'chromosome / start / end / num_motifs / median_llr / llr_list / pos_list'
	[DEBUG]: Input file type: Interval_Aggregate
Traceback (most recent call last):
  File "/home/tylerstevenson/miniconda3/lib/python3.7/site-packages/pycoMeth/Meth_Comp.py", line 127, in Meth_Comp
    raise ValueError (f"Invalid field {fp.colnames} in file {fn}")
ValueError: Invalid field ['chromosome', 'start', 'end', 'num_motifs', 'median_llr', 'llr_list', 'pos_list', 'byte_len'] in file results/methylation/pycometh_int_agg/test2.tsv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tylerstevenson/miniconda3/bin/pycoMeth", line 8, in <module>
    sys.exit(main())
  File "/home/tylerstevenson/miniconda3/lib/python3.7/site-packages/pycoMeth/__main__.py", line 115, in main
    args.func(**vars(args))
  File "/home/tylerstevenson/miniconda3/lib/python3.7/site-packages/pycoMeth/Meth_Comp.py", line 216, in Meth_Comp
    log_dict(stats_results.counter, log.info, "Results summary")
UnboundLocalError: local variable 'stats_results' referenced before assignment
```
Odd as it recognises it as a `Interval_Aggregate` file type, but then errors with an invalid field!

Thanks!

**Comment by a-slide** [comment]
Great to know that this older version is not supported.
I actually checked in pycoMeth doc and is is written that version Nanopolish  0.10+ is required 
[see installation doc](https://a-slide.github.io/pycoMeth/installation/)
Thanks for digging to the bottom.

**Comment by lab-rat-kid** [comment]
Thanks, I hadn't noticed I was using an old version of nanopolish! :)
