### ISSUE TITLE
Comp_report exiting with invalid file input type from Interval_Aggregate

### ISSUE THREAD

**Issue by dithiii** [a-slide/pycoMeth#48]
Hi I'm getting an error with Comp_report not reading my Interval_Aggregate input file (looks fine in .tsv and .bed format). Not sure where the problem is. Here's the first 3 lines of the Interval_aggregate file, and then the error from Comp_report.
```
head -n 3 barcode01.Interval_Aggregate.tsv
chromosome	start	end	num_motifs	median_llr	llr_list	pos_list
chr1	125175000	125180000	11	1.92	[1.92,5.855,4.945,5.065,1.1,0.385,1.79]	[125179758,125179784,125179833,125179863,125179882,125179925,125179987]
chr1	125180000	125185000	43	3.11	[2.08,4.8,2.52,5.315,2.53,1.16,3.965,3.955,4.94,4.49,5.91,1.86,2.475,0.31,2.83,3.11,2.035,-0.24,2.895,3.65,4.39,6.54,-0.37,3.54,3.905]	[125180008,125180032,125180060,125180083,125180104,125180154,125180187,125180226,125180252,125180301,125180331,125180393,125180419,125180471,125180575,125180606,125180624,125180650,125180682,125180700,125180723,125180746,125180764,125180800,125180821]
```

**Here's the error with Comp_report**
```
pycoMeth Comp_Report -i barcode01.Interval_Aggregate.tsv -g ~/Desktop/genomes/Homo_sapiens.GRCh38.101.gff3 -f ~/Desktop/genomes/hg38softmasked/hg38softmasked.fa --report_non_significant --verbose
## Checking options and input files ##
	[DEBUG]: Options summary
	[DEBUG]: 	Package name: pycoMeth
	[DEBUG]: 	Package version: 0.4.25
	[DEBUG]: 	Timestamp: 2020-11-02 15:43:48.841354
	[DEBUG]: 	methcomp_fn: barcode01.Interval_Aggregate.tsv
	[DEBUG]: 	gff3_fn: /home/cfaulk/Desktop/genomes/Homo_sapiens.GRCh38.101.gff3
	[DEBUG]: 	ref_fasta_fn: /home/cfaulk/Desktop/genomes/hg38softmasked/hg38softmasked.fa
	[DEBUG]: 	outdir: ./
	[DEBUG]: 	n_top: 100
	[DEBUG]: 	max_tss_distance: 100000
	[DEBUG]: 	pvalue_threshold: 0.01
	[DEBUG]: 	min_diff_llr: 1
	[DEBUG]: 	n_len_bin: 500
	[DEBUG]: 	api_mode: False
	[DEBUG]: 	export_static_plots: False
	[DEBUG]: 	report_non_significant: True
	[DEBUG]: 	verbose: True
	[DEBUG]: 	quiet: False
	[DEBUG]: 	progress: False
	[DEBUG]: 	kwargs
	[DEBUG]: 		subcommands: Comp_Report
	[DEBUG]: 		func: <function Comp_Report at 0x7fcecf1145f0>
## Loading and preparing data ##
	Loading Methcomp data from TSV file
Traceback (most recent call last):
  File "/home/cfaulk/miniconda3/envs/pycoMeth/bin/pycoMeth", line 8, in <module>
    sys.exit(main())
  File "/home/cfaulk/miniconda3/envs/pycoMeth/lib/python3.7/site-packages/pycoMeth/__main__.py", line 116, in main
    args.func(**vars(args))
  File "/home/cfaulk/miniconda3/envs/pycoMeth/lib/python3.7/site-packages/pycoMeth/Comp_Report.py", line 96, in Comp_Report
    raise pycoMethError ("Invalid input file type passed. Expecting Meth_Comp TSV file generated from samples processed with Interval_Aggregate")
pycoMeth.common.pycoMethError: Invalid input file type passed. Expecting Meth_Comp TSV file generated from samples processed with Interval_Aggregate

```

**Comment by dithiii** [comment]
Nevermind. I didn't read the instructions very well.
